# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task: dev

  dev:
    deps:
      - backend
      - frontend

  backend:
    cmds:
      - air

  frontend:
    dir: ./frontend
    cmds:
      - bun run dev

  goose:
    env:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: postgres://postgres:postgres@localhost:5454/postgres
      GOOSE_MIGRATION_DIR: ./migrations
      GOOSE_TABLE: custom.goose_migrations
    cmds:
      - goose {{.ARGS}}