# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task: dev

  dev:
    deps:
      - backend
      - frontend

  backend:
    cmds:
      - air

  frontend:
    dir: ./frontend
    cmds:
      - bun run dev
